### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by m-ferrero**
Hello, I've added the italian translation to the project.

### CODE REVIEW

**Comment by jdede** [comment]
Nice, thank you!

**Comment by jdede** [comment]
Can you give me a translation for the thunderbird add-on webpage (max 250 chars):
"""
WarnAttachment shows an additional dialog to confirm opening of potentially dangerous attachments. Some attachments like executables etc. are completely blocked. This reduces the risk of malware especially for inexperienced users.
"""
Thanks

**Comment by m-ferrero** [comment]
Hello, thanks for the pull and the great plugin, it will be a life saver!

Sure, here the translation:
"""
WarnAttachment mostra una finestra di dialogo chiedendo conferma dell'apertura di allegati potenzialmente dannosi. Alcuni allegati come eseguibili ecc. vengono bloccati. Questo riduce il rischio di malware, in particolare per gli utenti inesperti.
"""

I had to slightly change the wording to remain below 250 chars

**Comment by jdede** [comment]
Perfect, added. Thanks

**Pull request merged**
