### PR TITLE
Support AttachmentInfo in system module.

### PR DESCRIPTION
**Pull request by arai-a**
https://bugzilla.mozilla.org/show_bug.cgi?id=1696777 moved AttachmentInfo from the global variable to a system module.

this is another part of https://github.com/jdede/WarnAttachment/issues/20

with both https://github.com/jdede/WarnAttachment/pull/21 and this patch, I see the dialog when opening `.doc` file.

### CODE REVIEW

**Comment by arai-a** [comment]
err, sorry, this was wrong.
given it's moved to a system module, modification should happen only once

**Comment by jdede** [comment]
Should line 4 be a var Services instead of a const Services? Showing an error if I try to run it with a const...

**Comment by jdede** [comment]
Another maybe minor thing: When testing with tb 115 and I try to open a file with a warning, I will get the debug message "TypeError: browsingContext is undefined". In 102, it works. Is there a change in the handler?

**Comment by arai-a** [comment]
> Should line 4 be a var Services instead of a const Services? Showing an error if I try to run it with a const...

it's handled by https://github.com/jdede/WarnAttachment/pull/21, and I've rebased this PR branch onto it.

> Another maybe minor thing: When testing with tb 115 and I try to open a file with a warning, I will get the debug message "TypeError: browsingContext is undefined". In 102, it works. Is there a change in the handler?

There's new parameter.  I've fixed the patch to pass it through.

https://searchfox.org/comm-central/rev/78245f927ad4c32e6896f5ceee7483083f90bf59/mail/modules/AttachmentInfo.sys.mjs#138-145
```js
/**
 * Open this attachment.
 *
 * @param {integer} [browsingContextId]
 *   The browsingContext of the browser that this attachment is being opened
 *   from.
 */
async open(browsingContext) {
```

**Review by jdede — APPROVED** [review]
Good work. Thanks a lot

**Pull request merged**
